In [55]:
import pandas as pd 
import numpy as np

In [56]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa', 'profile_score', 'lpa'])
df

,cgpa,profile_score,lpa
0,8,8,4
1,7,9,5
2,6,10,6
3,5,12,7


In [57]:
def perameter_init(layers):
    perameters = {}
    layer_dim = len(layers)
    for i in range(1,layer_dim):
        perameters[f'w{i}'] = np.ones((layers[i-1],layers[i]))*0.1
        perameters[f'b{i}'] = np.zeros((layers[i],1))
        # print(i)
    return perameters

In [58]:
def linear(w,b,prv_layer):
    y_hat = np.dot(w.T,prv_layer) + b
    return y_hat

In [59]:
len(perameter_init([2,3,2,1]))

6

In [60]:
def forward_propagation(X,perameters):
    total_layer = len(perameters) // 2
    A = X 
    prv_layer_output = {}
    counter = 0
    output = 1
    for i in range(1,total_layer+1):
        if counter == 0 :
            prv_layer = A
            w = perameters[f'w{i}']
            b = perameters[f'b{i}']
            
            A = linear(w,b,prv_layer)
            counter+=1
        else: 
            prv_layer_output[f'o{i}'] = A
            w = perameters[f'w{i}']
            b = perameters[f'b{i}']
            
            # print(prv_layer_output[f'o{i}'])
                      
            A = linear(w,b,prv_layer_output[f'o{i}'])  
            counter+=1
            output+=1
            
    return A,prv_layer_output

In [61]:
X = df.iloc[:,:-1].values[0].reshape(2,1)
y = df.iloc[:,-1].values[0]

In [62]:
X

array([[8],
       [8]])

In [63]:
perameter = perameter_init([2,3,2,1])
y_hat,prv_layer = forward_propagation(X,perameter)

In [64]:
y_hat

array([[0.096]])

In [65]:
perameter['b2'][1][0]

np.float64(0.0)

In [66]:
perameter['b1'][1][0]
# prv_layer['b3'][0][0]

np.float64(0.0)

In [67]:
X[1][0]

np.int64(8)

In [68]:
y_hat[0][0]

np.float64(0.09600000000000003)

In [69]:
perameter['b1'][2]

array([0.])

In [70]:
def update_weights(perameter,prv_layer,y_hat,X,y,n):
    # Layer 1 -> part 1
    perameter['w1'][0][0] =  perameter['w1'][0][0] - n * (((-2 * (y -y_hat[0][0])) * perameter['w3'][0][0] * perameter['w2'][0][0] * X[0][0]) + ((-2 * (y -y_hat[0][0])) * perameter['w3'][1][0]*perameter['w2'][0][1]*X[0][0]))
    perameter['w1'][1][0] =  perameter['w1'][1][0] - n * (((-2 * (y -y_hat[0][0])) * perameter['w3'][0][0] * perameter['w2'][0][0] * X[1][0]) + ((-2 * (y -y_hat[0][0])) * perameter['w3'][1][0]*perameter['w2'][0][1]*X[1][0]))
    perameter['b1'][0][0] =  perameter['b1'][0][0] - n * ((-2 * (y -y_hat[0][0])) *  perameter['w3'][0][0] * perameter['w2'][0][0])           + ((-2 * (y -y_hat[0][0])) * perameter['w3'][1][0]*perameter['w2'][0][1])
    
    # Layer 1 -> part 2
    perameter['w1'][0][1] =  perameter['w1'][0][1] - n * (((-2 * (y -y_hat[0][0])) * perameter['w3'][0][0] * perameter['w2'][1][0] * X[0][0]) + ((-2 * (y -y_hat[0][0])) * perameter['w3'][1][0]*perameter['w2'][1][1]*X[0][0]))
    perameter['w1'][1][1] =  perameter['w1'][1][1] - n * (((-2 * (y -y_hat[0][0])) * perameter['w3'][0][0] * perameter['w2'][1][0] * X[1][0]) + ((-2 * (y -y_hat[0][0])) * perameter['w3'][1][0]*perameter['w2'][1][1]*X[1][0]))
    perameter['b1'][1][0] =  perameter['b1'][1][0] - n * (((-2 * (y -y_hat[0][0])) * perameter['w3'][0][0] * perameter['w2'][1][0])           + ((-2 * (y -y_hat[0][0])) * perameter['w3'][1][0]*perameter['w2'][1][1]))
    
    # Layer 1 -> part 3
    
    perameter['w1'][0][2] = perameter['w1'][0][2] - n * (((-2 * (y -y_hat[0][0])) * perameter['w3'][0][0] * perameter['w2'][2][0] * X[0][0]) + ((-2 * (y -y_hat[0][0])) * perameter['w3'][1][0]*perameter['w2'][2][1]*X[1][0]))
    perameter['w1'][1][2] = perameter['w1'][1][2] - n * (((-2 * (y -y_hat[0][0])) * perameter['w3'][0][0] * perameter['w2'][2][0] * X[0][0]) + ((-2 * (y -y_hat[0][0])) * perameter['w3'][1][0]*perameter['w2'][2][1]*X[1][0]))
    perameter['b1'][2][0] = perameter['b1'][2][0] - n * (((-2 * (y -y_hat[0][0])) * perameter['w3'][0][0] * perameter['w2'][2][0])           + ((-2 * (y -y_hat[0][0])) * perameter['w3'][1][0]*perameter['w2'][2][1]))
    
    # layer 2 part 1
    perameter['w2'][0][0] = perameter['w2'][0][0] -  n * (-2 *(y-y_hat[0][0]) * perameter['w3'][0][0]*prv_layer['o2'][0][0])
    perameter['w2'][1][0] = perameter['w2'][1][0] -  n * (-2 *(y-y_hat[0][0]) * perameter['w3'][0][0]*prv_layer['o2'][1][0])
    perameter['w2'][2][0] = perameter['w2'][2][0] -  n * (-2 *(y-y_hat[0][0]) * perameter['w3'][0][0]*prv_layer['o2'][2][0])
    perameter['b2'][0][0] = perameter['b2'][0][0] -  n * (-2 *(y-y_hat[0][0]) * perameter['w3'][0][0])
    
    # layer 2 part 2
    perameter['w2'][0][1] = perameter['w2'][0][1] - n * (-2 * (y-y_hat[0][0]) * perameter['w3'][1][0]*prv_layer['o2'][0][0])
    perameter['w2'][1][1] = perameter['w2'][1][1] - n * (-2 * (y-y_hat[0][0]) * perameter['w3'][1][0]*prv_layer['o2'][1][0])
    perameter['w2'][2][1] = perameter['w2'][2][1] - n * (-2 * (y-y_hat[0][0]) * perameter['w3'][1][0]*prv_layer['o2'][2][0])
    perameter['b2'][1][0] = perameter['b2'][1][0] - n * (-2 * (y-y_hat[0][0]) * perameter['w3'][1][0])
    
    #layer 3 
    perameter['w3'][0][0] = perameter['w3'][0][0] - n * (-2 * (y- y_hat[0][0]) * prv_layer['o3'][0][0])
    perameter['w3'][1][0] = perameter['w3'][1][0] - n * (-2 * (y- y_hat[0][0]) * prv_layer['o3'][1][0])
    perameter['b3'][0][0] = perameter['b3'][0][0] - n * (-2 * (y- y_hat[0][0]))
    

In [71]:
perameter = perameter_init([2,3,2,1])
# y_hat,prv_layer = forward_propagation(X,perameter)
epochs = 100
for _ in range(epochs):
    loss = []
    for i in range(df.shape[0]):
        X = df.iloc[:,:-1].values[i].reshape(2,1)
        y = df.iloc[:,-1].values[i]
        y_hat,prv_layer = forward_propagation(X,perameter)
        # print(y)
        # print(y_hat)
        # print(X)
        # print(prv_layer)
        update_weights(perameter,prv_layer,y_hat,X,y,0.001)
        loss.append((y-y_hat)**2)
    print(f'Loss epochs {_} {np.mean(loss)}')
perameter
    

Loss epochs 0 30.149720406525148
Loss epochs 1 29.35871841440983
Loss epochs 2 28.508313897858898
Loss epochs 3 27.54068695854766
Loss epochs 4 26.31947628922422
Loss epochs 5 24.5576843167606
Loss epochs 6 21.72341007675647
Loss epochs 7 17.07033906597856
Loss epochs 8 10.444460402784628
Loss epochs 9 4.184019140298849
Loss epochs 10 1.4144809768573596
Loss epochs 11 1.070320259903501
Loss epochs 12 1.1368144373138707
Loss epochs 13 1.166635531215197
Loss epochs 14 1.1675839933358105
Loss epochs 15 1.1595160346289137
Loss epochs 16 1.1490449430224732
Loss epochs 17 1.1379758243552227
Loss epochs 18 1.1267773763849998
Loss epochs 19 1.1155683300168309
Loss epochs 20 1.1043772983629978
Loss epochs 21 1.09320989834383
Loss epochs 22 1.0820659831761839
Loss epochs 23 1.0709440530251313
Loss epochs 24 1.0598423797835759
Loss epochs 25 1.0487592913566164
Loss epochs 26 1.0376932413961064
Loss epochs 27 1.026642824466376
Loss epochs 28 1.0156067774628934
Loss epochs 29 1.0045839776756416
Los

{'w1': array([[ 0.16994598, -0.06905345,  0.32252401],
        [ 0.26362579,  0.69569916,  0.32252401]]),
 'b1': array([[-7.03071144],
        [ 0.02186116],
        [ 0.02366039]]),
 'w2': array([[0.07502536, 0.07502536],
        [0.49134462, 0.49134462],
        [0.32294023, 0.32294023]]),
 'b2': array([[0.07063985],
        [0.07063985]]),
 'w3': array([[0.57670592],
        [0.57670592]]),
 'b3': array([[0.34685575]])}

In [72]:
perameter

{'w1': array([[ 0.16994598, -0.06905345,  0.32252401],
        [ 0.26362579,  0.69569916,  0.32252401]]),
 'b1': array([[-7.03071144],
        [ 0.02186116],
        [ 0.02366039]]),
 'w2': array([[0.07502536, 0.07502536],
        [0.49134462, 0.49134462],
        [0.32294023, 0.32294023]]),
 'b2': array([[0.07063985],
        [0.07063985]]),
 'w3': array([[0.57670592],
        [0.57670592]]),
 'b3': array([[0.34685575]])}